Add docker
Vladimir01082023/java-shareit pull request #4
Opened 2024-07-29 20:54 UTC by Vladimir01082023

2024-08-02 05:03 UTC, z8q requested changes

2024-08-02 05:03 UTC, z8q commented on server/src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
>      public Booking approveBooking(@PathVariable("bookingId") Long bookingId,
В BookingController во всех методах стоит возвращать dto вместо модели

2024-08-04 19:30 UTC, Vladimir01082023 commented
Здравствуйте. Проблема с гитом. Приклепляю ссылку на чат в пачке с проблемой. https://app.pachca.com/chats/?thread_message_id=302180822&sidebar_message=305060140

2024-08-05 17:42 UTC, z8q requested changes

2024-08-05 17:42 UTC, z8q commented on .github/workflows/build.sh
> +cp -rf ./tests/checkstyle.xml ./checkstyle.xml
Нужно поправить красную сборку

2024-08-05 19:38 UTC, closed without merging